name: Docker Image Build and Publish to ACR
on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "src/**"
jobs:
  Docker-Build-Push:
    steps:
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${ vars.ACR_LOGIN_SERVER }
          username: $${{ vars.AZURE_CLIENT_ID }}
          password: $${{ secrets.AZURE_CLIENT_SECRET }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${acr_login_server}/$${{ github.event.repository.name }}:latest
