apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-sc
  labels:
    app: python-sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-sc
  template:
    metadata:
      labels:
        app: python-sc
    spec:
      imagePullSecrets:
        - name: ignitedemo-acr
      containers:
        - name: python-sc
          image: ignitedemoacr.azurecr.io/python-sc:latest
          ports:
            - containerPort: 8080
