apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-sc
  labels:
    app: python-sc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-sc
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: python-sc
          image: ignitedemoacr.azurecr.io/python-sc:0.0.0
          ports:
            - containerPort: 8080
