apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-sc
  labels:
    app: python-sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-sc
  template:
    metadata:
      labels:
        app: python-sc
    spec:
      imagePullSecrets:
        - name: ignitedemo-acr
      containers:
        - name: python-sc
          imagePullPolicy: Always
          image: ignitedemoacr.azurecr.io/python-sc@sha256:82dd60b081c6a5c9c201876d26827550490a787b821bc60d97289944ce52a3ef
          ports:
            - containerPort: 8080
