apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-sc
  labels:
    app: python-sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-sc
  template:
    metadata:
      labels:
        app: python-sc
    spec:
      imagePullSecrets:
        - name: ignitedemo-acr
      containers:
        - name: python-sc
          imagePullPolicy: Always
          # image: ignitedemoacr.azurecr.io/python-sc@sha256:e16b8687f064f7c7b116d9856955641ad9b0794a54861acec570204a15b0abfc
          image: ignitedemoacr.azurecr.io/python-sc:latest
          ports:
            - containerPort: 8080
