apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ignitedemo-acr
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ignitedemo-acr
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ .dockerconfigjson | toString }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: acr
        property: dockerconfigjson
