name: Docker Image Build and Publish to ACR
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "app/**"
jobs:
  Docker-Build-Push:
    permissions:
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ACR_LOGIN_SERVER }}
          username: ${{ vars.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: Build and push image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.ACR_LOGIN_SERVER }}/${{ github.event.repository.name }}:latest
      - name: Attest build provenance
        id: attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ vars.ACR_LOGIN_SERVER }}/${{ github.event.repository.name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
