name: Build and Publish Image
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "app/**"
jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ACR_LOGIN_SERVER }}
          username: ${{ vars.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and push staging image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.ACR_LOGIN_SERVER }}/${{ github.event.repository.name }}:latest
